/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Report = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : IDL.Int,
  'corruption_type' : IDL.Text,
  'department' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'submitReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Report],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : IDL.Int,
    'corruption_type' : IDL.Text,
    'department' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'submitReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Report],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };